### ISSUE TITLE
'Help' command results in 'Sorry, I don't know how to do that yet.'

### ISSUE THREAD

**Issue by Yersi88** [stanford-oval/almond-cloud#1038]
Hello, I have problems with Almond on my Home assistant instalation. It won't respond to simple commands. Here is an example:

![image](https://user-images.githubusercontent.com/77145281/124382243-484f8500-dcbe-11eb-866b-0ba52f8f6f2d.png)

Also if I try to click on one of the Skills I get: 'almond.stanford.edu refused to connect.'
![image](https://user-images.githubusercontent.com/77145281/124382280-7cc34100-dcbe-11eb-97e8-700f39e44396.png)

Any help appreciated! 

LOGS:
`GET / 200 1510.434 ms - 4393
172.30.32.2 - - [04/Jul/2021:10:50:45 +0000] "GET / HTTP/1.1" 200 1707 "http://homeassistant.local:8123/core_almond" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
172.30.32.2 - - [04/Jul/2021:10:50:45 +0000] "GET /stylesheets/bootstrap.min.css HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /stylesheets/bootstrap.min.css 304 50.703 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:45 +0000] "GET /stylesheets/style.css HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /stylesheets/style.css 304 52.539 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:45 +0000] "GET /javascripts/validator.min.js HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /javascripts/validator.min.js 304 10.775 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:45 +0000] "GET /javascripts/jstz.min.js HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /javascripts/jstz.min.js 304 11.002 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:45 +0000] "GET /javascripts/shared.js HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /javascripts/shared.js 304 11.421 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:54 +0000] "GET /conversation HTTP/1.1" 200 1685 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /conversation 200 372.905 ms - 4820
172.30.32.2 - - [04/Jul/2021:10:50:54 +0000] "GET /stylesheets/bootstrap.min.css HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/conversation" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /stylesheets/bootstrap.min.css 304 4.490 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:54 +0000] "GET /stylesheets/style.css HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/conversation" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /stylesheets/style.css 304 5.129 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:54 +0000] "GET /stylesheets/spinner.css HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/conversation" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /stylesheets/spinner.css 304 6.290 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:54 +0000] "GET /stylesheets/conversation.css HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/conversation" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /stylesheets/conversation.css 304 6.030 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:54 +0000] "GET /javascripts/validator.min.js HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/conversation" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /javascripts/validator.min.js 304 6.075 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:54 +0000] "GET /javascripts/jstz.min.js HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/conversation" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /javascripts/jstz.min.js 304 5.289 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:54 +0000] "GET /javascripts/conversation.js HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/conversation" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /javascripts/conversation.js 304 5.879 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:54 +0000] "GET /javascripts/shared.js HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/conversation" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /javascripts/shared.js 304 6.597 ms - -
Sun, 04 Jul 2021 10:50:54 GMT express deprecated req.host: Use req.hostname instead at routes/api.js:245:24
172.30.32.2 - - [04/Jul/2021:10:50:54 +0000] "GET /images/bubble_almond.png HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/stylesheets/conversation.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /images/bubble_almond.png 304 3.814 ms - -
172.30.32.2 - - [04/Jul/2021:10:50:58 +0000] "GET /images/bubble_user.png HTTP/1.1" 304 0 "http://homeassistant.local:8123/api/hassio_ingress/alSBnCUlj1OzPPdCNtl2TSy9nk6fUklZ85VS7Qnydl0/stylesheets/conversation.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
GET /images/bubble_user.png 304 3.265 ms - -
Analyzed message into now => @org.thingpedia.builtin.thingengine.builtin.faq_reply param:question:Enum(about_almond_identity,about_almond_age,about_almond_how_are_you,about_almond_location,about_almond_comparison,about_almond_training,about_almond_partner,about_almond_junk,about_almond_preference,check_capability_home_assistant,check_capability_phone,general_help,iot_help,positive_emotion_thanks,positive_emotion_cool,abusive,revoke_consent,how_to_train,how_to_configure_skill,how_to_disable_skill,how_to_set_language,how_to_access_settings,how_to_use_wakeword,troubleshooting_home_assistant) = enum:general_help
Failed to parse beam 0: Class org.thingpedia.builtin.thingengine.builtin has no action faq_reply
Failed to parse beam 1: Class org.thingpedia.builtin.thingengine.builtin has no action faq_reply`

**Comment by gcampax** [comment]
What version of Almond did you use? If you're using the official add-on, that's still running Almond 1.0 which is no longer compatible with the latest version of the cloud services.
You'll need to install Almond 2.0 from [our repository](https://github.com/stanford-oval/almond-hassio-repository) or wait until Almond 2.0 is released officially as an add-on. See the [pull request](https://github.com/home-assistant/addons/pull/2042), which is currently waiting for approval from the Home Assistant developers.

**Comment by Yersi88** [comment]
I see, installed from your repo and all is working perfectly. Many thanks!
