### ISSUE TITLE
Cannot read property'name' of null.

### ISSUE THREAD

**Issue by tonyespinoza1** [stanford-oval/almond-cloud#1044]
on staging:

when i log into my account, genie is looping on the message, "Sorry, that did not work: Cannot read property'name' of null."

if i enter text, i get the following response, "Sorry, I had an error processing your command: Cannot read property'name' of null."

![image](https://user-images.githubusercontent.com/86493411/125876236-675c5847-419f-4ded-9559-8e0ba627b1f7.png)

**Comment by gcampax** [comment]
Filed also as https://github.com/stanford-oval/genie-toolkit/issues/695. Related PR at https://github.com/stanford-oval/genie-toolkit/pull/696.
