### ISSUE TITLE
(Staging & Production) SmartNews skill is down

### ISSUE THREAD

**Issue by tonyespinoza1** [stanford-oval/almond-cloud#1045]
![image](https://user-images.githubusercontent.com/86493411/125876321-1c10a3d3-a098-439f-8ccc-8ee5c3f712a9.png)

**Comment by gcampax** [comment]
Yeah this is an issue with SmartNews itself: on their end they need to run a daily batch job to generate the news audio, and sometimes they don't do that, or the script fails.

**Comment by tonyespinoza1** [comment]
Yes, I remember hearing about this.  Figured it was worth filing as a bug and assigning to someone to resolve.  Might Ed help?  Would you like me to reach out?

**Comment by gcampax** [comment]
I'm in touch with the SmartNews team on their slack. I'll talk to Ed as well.
