### ISSUE TITLE
(GitHub) "Installation Instructions" fails to load (404 Error)

### ISSUE THREAD

**Issue by tonyespinoza1** [stanford-oval/almond-cloud#1052]
Clicking link at bottom of [this page ](https://github.com/stanford-oval/almond-cloud)under, "Installation" leads to 404.  

"Installation
For detailed installation instructions, see [doc/installing-almond-cloud.md](https://github.com/stanford-oval/almond-cloud/blob/master/doc/installing-almond-cloud.md)"

**Comment by gcampax** [comment]
Fixed
