### ISSUE TITLE
Add a frontend classifier module

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-cloud#286]
Before throwing the sentence at Genie/decanlp (and until decanlp is trained with enough tasks that it can handle everything), we should run a simple frontend classifier to distinguish:

- commands
- questions
- chatty text
- insults / spam
- other

**Comment by ryachen01** [comment]
@gcampax I'm going to try to do this. Also, do you know of any datasets which contain data classified by commands, questions, or spam?

**Comment by gcampax** [comment]
I don't know of a single dataset that contains all of these.

We have [our own dataset](https://oval.cs.stanford.edu/releases/pldi19-dataset.tar.xz) that contains commands, but there are probably larger datasets out there you can leverage.
There are a lot of datasets such as WebQuestions or WikiQA (maybe others) that contains questions. 
For chatty text, I would look into end-to-end dialogue papers, for example those using the Switchboard or Ubuntu Tech Support datasets, and from those see if there are truly free text datasets we can leverage.

For spam I don't know of a good dataset of the top of my head. There are spam datasets of emails but they are not as relevant. OTOH, spam is usually recognizable by pattern, for example because it contains questionable links, or weird capitalization. You might be able to do something clever about it. 

Other is of course other, and that would be where the fun would be - for example using confidence scores to detect out of distribution data.

**Comment by gcampax** [comment]
Fixed by #294
