### ISSUE TITLE
Merge add new device and add new service

### ISSUE THREAD

**Issue by rayslxu** [stanford-oval/almond-cloud#326]
It confuses even us.

**Comment by gcampax** [comment]
What's "Add new device" / "Add new service" ? In My Almond or in Thingpedia?

**Comment by rayslxu** [comment]
In My Almond. I removed "add new device" in the production website for now given we don't have any "device" anyway.

**Comment by gcampax** [comment]
It should be enough to add `?class` to have both show up in the same page...

**Comment by gcampax** [comment]
Fixed by #336
