### ISSUE TITLE
Kubernetes jobs should be tagged to distinguish GPU vs CPU nodes

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-cloud#414]
Otherwise, if some non GPU pod is restarted while a GPU job is running, the scheduler might place the restarted pod on the GPU node, causing unnecessary disruption later when the GPU node is taken down.

**Comment by jgd5** [comment]
I forgot to add taints to gpu node. Will do so tomorrow.

**Comment by gcampax** [comment]
I added the taint "role=training" to the node manually now, but I didn't find how to add taints to the nodegroup with eksctl.

**Comment by jgd5** [comment]
Updated docs on how to create nodegroup taint using config file.
