### ISSUE TITLE
Train Almond failing to store new sentences

### ISSUE THREAD

**Issue by rickygv99** [stanford-oval/almond-cloud#435]
Train Almond was working fine and then suddenly started returning the following error:

`Failed to store the new sentence. You might need to wait until the natural language is fully trained.`

In the Chrome devtools console, it says `Failed to load resource: the server responded with a status of 400 ()`. The network tab only shows requests for resources from fontawesome and sourcesanspro.

Will update with more information if I find any.

**Comment by gcampax** [comment]
We discussed this on Slack, and the issue is in the actual ThingTalk code used, not in almond-cloud. Closing.
