### ISSUE TITLE
No useful error message when uploading device

### ISSUE THREAD

**Issue by rayslxu** [stanford-oval/almond-cloud#450]
Always show "Sorry that did not work   Code: TypeError" only

**Comment by gcampax** [comment]
Logs?

**Comment by rayslxu** [comment]
I mean I check logs every time, but other developers don't have access to the server right...

**Comment by gcampax** [comment]
I mean yes, but what are the logs in this case, so we can fix it.

**Comment by rayslxu** [comment]
#451
