### ISSUE TITLE
Getting examples by device kinds is broken

### ISSUE THREAD

**Issue by rayslxu** [stanford-oval/almond-cloud#459]
`SyntaxError: Unexpected token o in JSON at position 1`

**Comment by gcampax** [comment]
This is unexpected - we have tests for this.
What server, which API endpoint (v1 or v3), which device, and with what `Accept` header?

**Comment by rayslxu** [comment]
https://almond.stanford.edu/doc/thingpedia-api/#api-Cheatsheet-GetExamplesByKinds
production, v3, com.bing, tested on the documentation page

**Comment by gcampax** [comment]
Oh. The problem is the API tester. The API does not return JSON by default: you need to pass `Accept: application/json` if you want JSON, otherwise you get ThingTalk. The API tester does not like that...
