### ISSUE TITLE
Update-dataset job fails

### ISSUE THREAD

**Issue by jgd5** [stanford-oval/almond-cloud#469]
This is running with master and crowdie.stanford.edu/thingengine 

Starting update-dataset job 28 for model @null/en
Job 28 is now update-dataset
/usr/bin/node '--max_old_space_size=24000' '/opt/almond-cloud/main.js' 'run-training-task' '--task-name' 'update-dataset' '--job-id' '28' '--job-directory' 'file:///home/almond-cloud/training/jobs/28'
job 28: Dataset cleaned
job 28: /opt/almond-cloud/main.js:19
job 28: process.on('unhandledRejection', (up) => { throw up; });
job 28:                                            ^
job 28: Error: Parse error: unexpected token  in state 0, expected (,[,attimer,bookkeeping,edge,executor,monitor,now,policy,timer
job 28:     at ShiftReduceParser._helper (/opt/almond-cloud/node_modules/thingtalk/lib/nn-syntax/sr_parser_runtime.js:71:27)
job 28:     at ShiftReduceParser.parse (/opt/almond-cloud/node_modules/thingtalk/lib/nn-syntax/sr_parser_runtime.js:107:32)
job 28:     at Object.fromNN (/opt/almond-cloud/node_modules/thingtalk/lib/nn-syntax/index.js:19:19)
job 28:     at Promise.all.batch.map (/opt/almond-cloud/training/tasks/update-dataset.js:155:52)
job 28:     at Array.map (<anonymous>)
job 28:     at DatasetUpdater._typecheckParaphrasesAndOnline (/opt/almond-cloud/training/tasks/update-dataset.js:153:55)
job 28:     at process._tickCallback (internal/process/next_tick.js:68:7)
job 28: From previous event:
job 28:     at Object.withTransaction (/opt/almond-cloud/util/db.js:173:26)
job 28:     at DatasetUpdater.run (/opt/almond-cloud/training/tasks/update-dataset.js:237:18)
job 28:     at Object.main [as update-dataset] (/opt/almond-cloud/training/tasks/update-dataset.js:254:19)
job 28:     at Object.main (/opt/almond-cloud/training/run-training-task.js:117:36)
job 28:     at process._tickCallback (internal/process/next_tick.js:68:7)
Job 28 failed during task update-dataset: Error: Command exited with code 1
Error: Command exited with code 1
    at ChildProcess.child.on (/opt/almond-cloud/training/backends/local.js:41:32)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Completed update-dataset job 28 for model @null/en
Ignored email to thingpedia-admins@lists.stanford.edu with subject "Training Job 28 failed"

**Comment by gcampax** [comment]
How did you test this? Did you run the database migrations manually? Don't do this, it will mess with the automatic migration script...

**Comment by jgd5** [comment]
I was just issuing the default training request for testing:
```
curl -H 'Content-Type: application/json'   -H "Authorization: Bearer ${TOKEN}"   -d '{"forDevices": null}'   $HOST/jobs/create
```

I worked around by skipping `updata-dataset`.  I suppose will need to do this until the databse is migrated?

```
 curl -H 'Content-Type: application/json'   -H "Authorization: Bearer ${TOKEN}"   -d '{"forDevices": null, "jobType": "train-only"}'   $HOST/jobs/create
```

**Comment by gcampax** [comment]
No, I migrated the DB and tested it using the old staging infrastructure (manually installed in a server), and update-dataset works. Maybe try again?

**Comment by jgd5** [comment]
it works now.
