### ISSUE TITLE
Model evaluation fails

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-cloud#503]
On staging infra:

> Traceback (most recent call last):
  File "/usr/local/bin/decanlp", line 11, in <module>
    load_entry_point('decanlp', 'console_scripts', 'decanlp')()
  File "/opt/decanlp/decanlp/tool.py", line 58, in main
    main_fn(canned_argv)
  File "/opt/decanlp/decanlp/server.py", line 251, in main
    server.run()
  File "/opt/decanlp/decanlp/server.py", line 198, in run
    self._run_stdin()
  File "/opt/decanlp/decanlp/server.py", line 176, in _run_stdin
    sys.stdout.write(self.handle_request(line))
  File "/opt/decanlp/decanlp/server.py", line 116, in handle_request
    request = json.loads(line)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 27-28: surrogates not allowed
Worker local/0 exited

There seems to be some UTF-8 encoding error. Perhaps something is encoded as two surrogate pairs instead of one UTF-8 character.

**Comment by gcampax** [comment]
I found the culprit sentence is:
```
byt låt
```
(which Google says is Swedish for "change song").

I don't know how it ended up in the staging dataset. Regardless, it is correctly UTF-8 encoded in the dataset, and correctly UTF-8 in the dataset file.

I suspect one of two things:
- `aws sync` is converting from UTF-8 encoding to some legacy encoding during download
- `decanlp` is converting from legacy encoding to UTF-8, and choking on something that is already UTF-8
(nodejs ignores the character encoding anywhere and just blindly assumes UTF-8, which is the correct thing to do IMHO).

I cannot unfortunately reproduce the problem locally, even with `LC_ALL=C`. But I remember in the tokenizer I had to set `env LANG=C.UTF-8`, maybe we need the same in our images?

**Comment by jgd5** [comment]
I found something in the python3 doc for sys.stdin https://docs.python.org/3/library/sys.html:

> The character encoding is platform-dependent. Non-Windows platforms use the locale encoding (see locale.getpreferredencoding()).

```
 docker run  --entrypoint "python3" stanfordoval/almond-cloud:latest-decanlp \
        -c 'import locale; print(locale.getpreferredencoding())'
ANSI_X3.4-1968
```

The default locale in decanlp seems to be ANSI.  How about setting environment  `PYTHONIOENCODING`  to override stdio encoding to utf-8 as recommended in the doc?

```
PYTHONIOENCODING=UTF-8
```

**Comment by gcampax** [comment]
Yeah we should be UTF-8 everything, so making sure Python uses that seems the best option.
