### ISSUE TITLE
Training daemon can get stuck and not recognize the job failed

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-cloud#512]
This is the situation right now in staging. Job 269 failed but the training server is stuck.

Logs say:
```
Job 269 is now prepare-training-set
processing job training-job-269-prepare-training-set
wating for job status
processing job training-job-269-prepare-training-set
wating for job status
watch jobs error: null
```

**Comment by jgd5** [comment]
watch terminated normally (error: null) but unfortunately, the failed condition wasn't available when we process the job state.  I'll add retries to watch jobs and throw an error if retry fails.

**Comment by gcampax** [comment]
This is getting messy, though, with more and more hacks. Maybe with should switch to a more packaged solution? I hear https://github.com/volcano-sh/volcano is good, and then we could just have our training code as a tiny layer to manager our logic (reading the list of models, computing dependencies, progress, etc.).

**Comment by jgd5** [comment]
I’ll take a look at volcano.

**Comment by jgd5** [comment]
I looked through volcano project. My initial impression is that it is designed for large scale jobs where kubernetes scheduler is not efficient at managing resources for multiple ML training jobs with large number of nodes.  At our current stage, we probably don't need these features yet. Kubernetes job scheduler is probably good enough.  Also, this project is at quite an early stage, which may be unstable for production use.  We may end up spending more time tracking down their bugs.

If you want to look for an existing workflow solutions on top of k8s. There are a couple mature projects out there:

 https://github.com/apache/airflow and https://github.com/argoproj/argo .  

I've used argo in the past and kubeflow  pipeline (https://www.kubeflow.org/docs/pipelines/overview/pipelines-overview/)  is also built on top of argo.   But neither has a js client api and their REST APIs are still experimental.  It also doesn't mean we won't have issues with their library too.  In the past we had to work around the bugs we found in argo.  

I think our workflow is quite simple right now.  If the job dependencies becomes more complicated, we may want to look into existing workflow libraries. Meanwhile, I will continue to patch our current solution as we hit more corner cases.  Let me know your thoughts.

**Comment by gcampax** [comment]
Ha! The way I discovered volcano was looking a kubeflow. Maybe they switched backends recently?
Anyway I don't mind keeping our dependencies lean, and avoiding complexity. I'm just worried about a growing chunk of code that gets tested only in staging (which is routinely broken for unrelated reasons). It was fine when the k8s code was small and self contained...

**Comment by jgd5** [comment]
Kubeflow is using both but for different purposes.  Looks like volcano is used to replace k8 scheduler with advanced gang scheduling for large scale distributed training jobs, like how to efficiently assign cpu/memory/gpu to master/ps/worker workgroups.  Argo is used at higher level for workflow management in kubeflow pipeline, such as executing the job dependency graph and funneling artifacts from one job to next.  

We might need gang scheduler in the future if we move to distributed training.  What we have right now is a simple sequential workflow.  I think the complexity is manageable right now.  Staging is getting more stable . We are getting there :)
