### ISSUE TITLE
no funciona la configuracion de home assistant

### ISSUE THREAD

**Issue by maeztus** [stanford-oval/almond-cloud#734]
quiero habilitar home assistant y cuando entro en la habilidad me da error

**Comment by gcampax** [comment]
Hi @maeztus,

Thanks for your report. Apologies for replying in English, but none of us speak Spanish.

As for your problem with Home Assistant, you should start the configuration from the Home Assistant side, following the instructions here: https://www.home-assistant.io/integrations/almond/
That will make sure your Home Assistant has a cloud URL that Almond can connect to.

**Comment by maeztus** [comment]
gracias. si, lo hice y funciono.
