### ISSUE TITLE
Update Almond website content

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-cloud#966]
By the stable release, we probably should:
- [ ] redo the scrolling screenshots (most commands are not supported, and those are supported are not very useful)
- [ ] update the videos (but we can keep Michael's)
- [ ] drop the "Our Goal" section and replace it with something clearer and more product oriented
- [ ] update the Get Involved page with more recent projects, or link straight to https://wiki.almond.stanford.edu/contributing
- [ ] update the Get Almond page to talk about Home Assistant
- [ ] maybe remove the footer?

**Comment by almakantara** [comment]
let's think about it, for Genie is needed a total redesign in contents and appearence, so we could focus directly on what we want for that, and keep al the rest on the actual almond to be reviewed/reused later on, even thinking to keep the project/open source content there, and on genie just focus on the "product" as first outcome of the lab/project.

So on the Almond website right now we can do some quick cleaning were needed

**Comment by gcampax** [comment]
Done enough.
